name: projectvg-llm-server

volumes:
  projectvg-llm-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH:-../data}/logs/llm-server
  projectvg-llm-cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH:-../data}/cache/llm-server

services:
  llm-server:
    build: .
    container_name: llm-server
    ports:
      - "7930:8080"
    environment:
      # 글로벌 환경 설정
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FORMAT=${LOG_FORMAT:-json}
      # 서버 설정
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - LOG_FILE=/app/logs/app.log
    volumes:
      - projectvg-llm-logs:/app/logs
      - projectvg-llm-cache:/app/cache
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"